export const ADD_TODO_LOADING = 'ADD_TODO_LOADING';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const GET_TODO_LOADING = 'GET_TODO_LOADING';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_ERROR = 'GET_TODO_ERROR';

export const GET_TODO_DETAIL_LOADING = 'GET_TODO_DETAIL_LOADING';
export const GET_TODO_DETAIL_SUCCESS = 'GET_TODO_DETAIL_SUCCESS';
export const GET_TODO_DETAIL_ERROR = 'GET_TODO_DETAIL_ERROR';

export const EDIT_TODO_LOADING = 'EDIT_TODO_LOADING';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_ERROR = 'EDIT_TODO_ERROR';


